In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("CarPrice_Assignment.csv")

In [4]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0


In [5]:
df.shape

(205, 26)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    str    
 3   fueltype          205 non-null    str    
 4   aspiration        205 non-null    str    
 5   doornumber        205 non-null    str    
 6   carbody           205 non-null    str    
 7   drivewheel        205 non-null    str    
 8   enginelocation    205 non-null    str    
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    str    
 15  cylindernumber    205 non-null    str    
 16  enginesize        205 non-null    int64  
 17  fuelsyst

In [7]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='str')

In [8]:
df.dtypes

car_ID                int64
symboling             int64
CarName                 str
fueltype                str
aspiration              str
doornumber              str
carbody                 str
drivewheel              str
enginelocation          str
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype              str
cylindernumber          str
enginesize            int64
fuelsystem              str
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [9]:
df.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000


In [10]:
categorical_columns = df.select_dtypes(include="object").columns

categorical_columns

C:\Users\AKSHAY\AppData\Local\Temp\ipykernel_26792\1797605437.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include="object").columns


Index(['CarName', 'fueltype', 'aspiration', 'doornumber', 'carbody',
       'drivewheel', 'enginelocation', 'enginetype', 'cylindernumber',
       'fuelsystem'],
      dtype='str')

In [11]:
y = df["price"]

In [12]:
X = df.drop("price", axis=1)

In [13]:
X.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22


In [14]:
X = df.select_dtypes(include=["int64", "float64"])

In [15]:
X = X.drop(columns=["price", "car_ID"])

In [16]:
X.head()

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27
1,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27
2,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,5000,19,26
3,2,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102,5500,24,30
4,2,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115,5500,18,22


In [17]:
X = X.to_numpy()
y = y.to_numpy()

In [18]:
print(X.shape)
print(y.shape)

(205, 14)
(205,)


In [19]:
np.random.seed(42)

In [20]:
indices = np.random.permutation(len(X))

In [21]:
X = X[indices]
y = y[indices]

In [22]:
print(X.shape)
print(y.shape)

(205, 14)
(205,)


In [23]:
split_index = int(0.8 * len(X))

In [24]:
X_train = X[:split_index]
X_test = X[split_index:]

y_train = y[:split_index]
y_test = y[split_index:]

In [25]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(164, 14)
(41, 14)
(164,)
(41,)


In [26]:
X_train[:5]

array([[ 0.000e+00,  1.035e+02,  1.890e+02,  6.690e+01,  5.570e+01,
         3.230e+03,  2.090e+02,  3.620e+00,  3.390e+00,  8.000e+00,
         1.820e+02,  5.400e+03,  1.600e+01,  2.200e+01],
       [ 0.000e+00,  9.950e+01,  1.782e+02,  6.790e+01,  5.200e+01,
         3.053e+03,  1.310e+02,  3.130e+00,  3.400e+00,  7.000e+00,
         1.600e+02,  5.500e+03,  1.600e+01,  2.200e+01],
       [ 0.000e+00,  9.720e+01,  1.734e+02,  6.520e+01,  5.470e+01,
         2.302e+03,  1.200e+02,  3.330e+00,  3.470e+00,  8.500e+00,
         9.700e+01,  5.200e+03,  2.700e+01,  3.400e+01],
       [ 3.000e+00,  9.910e+01,  1.866e+02,  6.650e+01,  5.610e+01,
         2.658e+03,  1.210e+02,  3.540e+00,  3.070e+00,  9.310e+00,
         1.100e+02,  5.250e+03,  2.100e+01,  2.800e+01],
       [-1.000e+00,  1.100e+02,  1.909e+02,  7.030e+01,  5.870e+01,
         3.750e+03,  1.830e+02,  3.580e+00,  3.640e+00,  2.150e+01,
         1.230e+02,  4.350e+03,  2.200e+01,  2.500e+01]])

In [27]:
mu = np.mean(X_train, axis=0)

In [28]:
mu

array([8.90243902e-01, 9.85298780e+01, 1.73306098e+02, 6.57890244e+01,
       5.37268293e+01, 2.52945732e+03, 1.24951220e+02, 3.32463415e+00,
       3.25768293e+00, 1.02903049e+01, 1.01579268e+02, 5.12134146e+03,
       2.55121951e+01, 3.10121951e+01])

In [29]:
sigma = np.std(X_train, axis=0)

In [30]:
sigma

array([1.23472222e+00, 5.96343717e+00, 1.23417430e+01, 2.10142264e+00,
       2.47613235e+00, 5.06258434e+02, 3.92067386e+01, 2.65909370e-01,
       3.11117866e-01, 4.18024148e+00, 3.76221563e+01, 4.91080844e+02,
       6.48214038e+00, 6.76882002e+00])

In [31]:
X_train = (X_train - mu) / sigma

In [32]:
X_test = (X_test - mu) / sigma

In [33]:
w = np.zeros(X_train.shape[1])
b = 0

In [34]:
predictions = X_train @ w + b

In [35]:
predictions[:5]

array([0., 0., 0., 0., 0.])

In [36]:
errors = predictions - y_train

In [37]:
squared_errors = errors ** 2

In [38]:
total_squared_error = np.sum(squared_errors)

In [39]:
m = len(y_train)

In [40]:
cost = total_squared_error / (2 * m)

In [41]:
cost

np.float64(113957753.35498138)

In [42]:
dj_db = np.sum(errors) / m

In [43]:
dj_dw = (X_train.T @ errors) / m

In [44]:
alpha = 0.01

In [45]:
w = w - alpha * dj_dw
b = b - alpha * dj_db

In [46]:
def compute_cost(X, y, w, b):
    m = len(y)
    predictions = X @ w + b
    errors = predictions - y
    cost = np.sum(errors ** 2) / (2 * m)
    return cost

In [47]:
def compute_gradient(X, y, w, b):
    m = len(y)
    errors = (X @ w + b) - y
    dj_dw = (X.T @ errors) / m
    dj_db = np.sum(errors) / m
    return dj_dw, dj_db

In [60]:

def gradient_descent(X, y, w, b, alpha, num_iterations):
    J_history = []

    for i in range(num_iterations):
        dj_dw, dj_db = compute_gradient(X, y, w, b)

        w = w - alpha * dj_dw
        b = b - alpha * dj_db

        J_history.append(compute_cost(X, y, w, b))

    return w, b, J_history


In [61]:

w, b, J_history = gradient_descent(
    X_train, y_train,
    np.zeros(X_train.shape[1]), 0,
    alpha=0.01,
    num_iterations=1000
)

predictions = X_test @ w + b

test_errors = predictions - y_test
mae = np.mean(np.abs(test_errors))
rmse = np.sqrt(np.mean(test_errors ** 2))

print("Initial cost:", J_history[0])
print("Final cost:", J_history[-1])
print("Test MAE:", mae)
print("Test RMSE:", rmse)


Initial cost: 109639037.23088928
Final cost: 4344815.228200334
Test MAE: 2865.1470461778545
Test RMSE: 3846.3382383026556


In [58]:

predictions = X_test @ w + b

print("Predicted prices:", predictions[:5])
print("Actual prices:", y_test[:5])


Predicted prices: [22004.06838321 19036.7475375  13824.58234517 18257.06156039
 12592.43480822]
Actual prices: [15690. 15040. 11549. 18420. 10795.]


In [62]:

test_errors = predictions - y_test

mae = np.mean(np.abs(test_errors))
rmse = np.sqrt(np.mean(test_errors ** 2))

print("Mean Absolute Error (MAE):", mae)
print("Root Mean Squared Error (RMSE):", rmse)


Mean Absolute Error (MAE): 2865.1470461778545
Root Mean Squared Error (RMSE): 3846.3382383026556


In [63]:

for i, cost in enumerate(J_history, start=1):
    print(f"Iteration {i}: Cost = {cost:.2f}")


Iteration 1: Cost = 109639037.23
Iteration 2: Cost = 105683204.68
Iteration 3: Cost = 102047589.14
Iteration 4: Cost = 98694915.05
Iteration 5: Cost = 95592608.07
Iteration 6: Cost = 92712193.73
Iteration 7: Cost = 90028773.25
Iteration 8: Cost = 87520566.53
Iteration 9: Cost = 85168513.74
Iteration 10: Cost = 82955928.01
Iteration 11: Cost = 80868192.63
Iteration 12: Cost = 78892497.05
Iteration 13: Cost = 77017606.69
Iteration 14: Cost = 75233662.35
Iteration 15: Cost = 73532005.15
Iteration 16: Cost = 71905024.08
Iteration 17: Cost = 70346022.91
Iteration 18: Cost = 68849104.24
Iteration 19: Cost = 67409068.37
Iteration 20: Cost = 66021325.09
Iteration 21: Cost = 64681816.78
Iteration 22: Cost = 63386951.32
Iteration 23: Cost = 62133543.61
Iteration 24: Cost = 60918764.54
Iteration 25: Cost = 59740096.46
Iteration 26: Cost = 58595294.38
Iteration 27: Cost = 57482352.08
Iteration 28: Cost = 56399472.57
Iteration 29: Cost = 55345042.27
Iteration 30: Cost = 54317608.55
Iteration 31: Co